name: create issue

on:
  schedule:
    - cron:  '0 0 1 */3 *'

jobs:
  build:
    name: create issue
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
